# Base
FROM python:3.10-buster

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE 1

RUN : "---------- install be build container deps ----------" \
    && apt-get update && pip install --upgrade pip && apt-get install -y \
    build-essential \
    libpq-dev \
    gettext \
    libev-dev \
    gcc \
    htop

RUN export DOCKER_DEFAULT_PLATFORM=linux/amd64

WORKDIR /project

RUN pip install poetry==1.7.1 --no-cache-dir
COPY pyproject.toml poetry.lock /project/
RUN poetry config installer.max-workers 10
RUN poetry config virtualenvs.create false \
    && poetry install --no-dev --no-interaction --no-ansi

# copy & prepare scripts
COPY ./scripts/entrypoint.sh /scripts/
RUN chmod +x /scripts/entrypoint.sh

COPY . /project
WORKDIR /project

ENTRYPOINT ["/scripts/entrypoint.sh"]
